import React, {ReactNode} from 'react'
import Head from 'next/head'
import Bottom from './bottom'
interface Props {
    children: React.ReactNode;
    elementType?: keyof JSX.IntrinsicElements;
  }
export default function Layout ({ children }: Props): JSX.Element {
    return (
      <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="stylesheet" href="https://use.typekit.net/itl2jeo.css"></link>
        </Head>
        <main>{children}</main>
      </>
    )
  }
